name: bolig_scraper
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - selenium
  - beautifulsoup4
  - tqdm
  - google-auth
  - google-auth-oauthlib
  - google-api-python-client
  - gspread
  - jsonschema
  - pip
  - pip:
    - pprintpp
    - python-vlc
    - re

